(* 
  Math Subset of LaTeX in EBNF
*)

expression  = term, { ("+" | "-"), term } ;

term        = power, { ("*" | "/"), power } ;

power       = prefix, [ "^", prefix ] ;

prefix		= [ "-" | "*" ], call;

call		= sqrt | factor;

factor      = number
            | constant
            | variable
            | "(", expression, ")" ;

frac        = "\frac", "{", expression, "}", "{", expression, "}"
            | "\frac", digit, digit;
            
sqrt        = "\sqrt", "{", expression, "}"
            | "\sqrt", "[", number, "]", "{", expression, "}";


(* 
  Basic Components
  ----------------
  These are low-level components, the small building blocks.
*)

number      = digit, { digit } ;

variable    = letter, { letter | digit } ;

constant    = "\pi"
            | "\epsilon" ;

letter      = "A" | "B" | "C" | "D" | "E" | "F" | "G"
            | "H" | "I" | "J" | "K" | "L" | "M" | "N"
            | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
            | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
            | "c" | "d" | "e" | "f" | "g" | "h" | "i"
            | "j" | "k" | "l" | "m" | "n" | "o" | "p"
            | "q" | "r" | "s" | "t" | "u" | "v" | "w"
            | "x" | "y" | "z" ;

digit       = "0" | "1" | "2" | "3" | "4" | "5"
            | "6" | "7" | "8" | "9" ;
