name: Go CI
on:
  push:
    paths-ignore:
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'frontend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          go-version-file: go.mod

      - name: Create dumb files for dist folder
        run: |
          mkdir -p frontend/dist
          touch frontend/dist/index.html

      - name: Lint
        uses: golangci/golangci-lint-action@v7

      - name: Build
        run: go build -v ./...

      - name: Test with the Gotestsum
        run: go test ./...
